import type { Task } from "../types/task";

export const initialTasks: Task[] = [
    {
        id: 1,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "A fazer",
        priority: "Alta",
        isChecked: false,
        createdAt: "10/10/2026",
    },
    {
        id: 2,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "A fazer",
        priority: "Alta",
        isChecked: false,
        createdAt: "10/10/2026",
    },
    {
        id: 3,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "Em andamento",
        priority: "Média",
        isChecked: false,
        createdAt: "10/10/2026",
    },
    {
        id: 4,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "Em andamento",
        priority: "Média",
        isChecked: false,
        createdAt: "10/10/2026",
    },
    {
        id: 5,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "Concluído",
        priority: "Baixa",
        isChecked: false,
        createdAt: "10/10/2026",
    },
    {
        id: 6,
        title: "Estudar React e TypeScript",
        description: "Aprofundar conhecimentos sobre Hooks, Context API e boas práticas de desenvolvimento.",
        status: "Concluído",
        priority: "Baixa",
        isChecked: false,
        createdAt: "10/10/2026",
    },
];
